エラーハンドリング

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -17,10 +17,10 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
 
     - name: Set up Python 3.10
-      uses: actions/setup-python@v3
+      uses: actions/setup-python@v4
       with:
         python-version: "3.10"
 
@@ -30,12 +30,20 @@ jobs:
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
     - name: Test with pytest
+      id: unit_test
       run: |
         pytest tests -v --cov=src --cov-report=html
       continue-on-error: true
 
     - name: Upload coverage
-      uses: actions/upload-artifact@v2
+      uses: actions/upload-artifact@v3
       with:
         name: htmlcov
         path: htmlcov
+
+    - name: Error handling
+      if: ${{ steps.unit_test.outcome == 'failure' }}
+      run: |
+        echo "Error handling"
+        echo ${{ steps.unit_test.outcome }}
+        exit 1
